site_name: My Docs
theme:
  name: material
extra_css:
  - css/extra.css
dev_addr: "127.0.0.1:8013"
copyright: "A P Oliver 2021- "
site_dir: "cid"
site_url: https://compisle.github.io/cid/
markdown_extensions:
  - pymdownx.emoji
nav:
  - Home: index.md
  - CompSci:
      - "Data Types": CompSci/DataTypes.md
      - "Testing": CompSci/testing.md
  - Policies:
      - "Plagiarism": "Departmental Policies/plagiarism.md"
      - "Workflow": "Departmental Policies/workflow.md"
  - Git:
      - Basics: "git/git-basics.md"
      - "Before You Start": "git/git-bys.md"
  - L3:
      - "Unit 03": "L3 Units/Unit03/Resources.md"
  - Design:
      - "Responsive Design": "ResponsiveDesign/responsiveDesign.md"
  - PDFs: pdf-from-markdown.md
  - "Induction": TechInd.md
  - "Welcome": Welcome.md
  